### ISSUE TITLE
Let's Encrypt SSL 인증서의 기간만료

### ISSUE THREAD

**Issue by scarlet9** [PoolC/Nagase#6]
`api.poolc.org` 서버의 SSL 인증서가 개시 시점 현재 2019. 7. 11.자로 만료되어서 
배경이미지, Footer 부분 로고를 포함한 이미지 리소스가 제대로 나타나지 않습니다.

**Comment by hellodhlyn** [comment]
인증서 갱신하였고, 앞으로는 자동 갱신되도록 조치하였습니다.
제보에 감사드립니다 :bowing_man:
